services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SEED_FROM_DB=true          # <-- turn on seeding
      - API_TOKEN=secret123        # <-- keep smoke-test happy
    volumes:
      - ./db.json:/app/db.json:ro  # seed file available inside container
